# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a13c70c6d79ef8e6a8f7d670fffd25250fa044be2c60eb2fe80d793651e1e6e0760fc6f8aef5efb0f49102fcb197a5bf693e5157f84d3b93324147a2aa0bc897

test:
  secret_key_base: fe4112b386268db9680c1b5ca3c9212c279e9cb953c3ece6b91a9b12820a7278cabc84f8ba667023ce55f3321c62da0adf3d11a79e7f2ea0fdfa255b3f9947b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
